name: Collect Crypto Data

on:
  schedule:
    # 매시간 정각에 실행 (UTC 기준)
    - cron: '0 * * * *'
  
  # 수동 실행도 가능
  workflow_dispatch:

jobs:
  collect-data:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Collect crypto data
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
        run: node scripts/collect-crypto-data.js
        
      - name: Report success
        if: success()
        run: |
          echo "✅ Data collection completed successfully at $(date)"
          
      - name: Report failure
        if: failure()
        run: |
          echo "❌ Data collection failed at $(date)"
          exit 1